package modelo.dto.hibernate;
// Generated 15 ene 2026, 19:44:17 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Autores generated by hbm2java
 */
public class Autores implements java.io.Serializable {

	private Integer idAutor;
	private Nacionalidades nacionalidades;
	private String nombre;
	private int nacimiento;
	private Integer muerte;
	private Set libroses = new HashSet(0);

	public Autores() {
	}

	public Autores(Nacionalidades nacionalidades, String nombre, int nacimiento) {
		this.nacionalidades = nacionalidades;
		this.nombre = nombre;
		this.nacimiento = nacimiento;
	}

	public Autores(Nacionalidades nacionalidades, String nombre, int nacimiento, Integer muerte, Set libroses) {
		this.nacionalidades = nacionalidades;
		this.nombre = nombre;
		this.nacimiento = nacimiento;
		this.muerte = muerte;
		this.libroses = libroses;
	}

	public Integer getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(Integer idAutor) {
		this.idAutor = idAutor;
	}

	public Nacionalidades getNacionalidades() {
		return this.nacionalidades;
	}

	public void setNacionalidades(Nacionalidades nacionalidades) {
		this.nacionalidades = nacionalidades;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getNacimiento() {
		return this.nacimiento;
	}

	public void setNacimiento(int nacimiento) {
		this.nacimiento = nacimiento;
	}

	public Integer getMuerte() {
		return this.muerte;
	}

	public void setMuerte(Integer muerte) {
		this.muerte = muerte;
	}

	public Set getLibroses() {
		return this.libroses;
	}

	public void setLibroses(Set libroses) {
		this.libroses = libroses;
	}

	@Override
	public String toString() {
		return "Autores [idAutor=" + idAutor + ", nacionalidades=" + nacionalidades + ", nombre=" + nombre
				+ ", nacimiento=" + nacimiento + ", muerte=" + muerte + ", libroses=" + libroses + "]";
	}
	
	
	

}
