package modelo.dto.hibernate;
// Generated 15 ene 2026, 19:44:17 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Generos generated by hbm2java
 */
public class Generos implements java.io.Serializable {

	private Integer idGenero;
	private String nombre;
	private Set libroses = new HashSet(0);

	public Generos() {
	}

	public Generos(String nombre) {
		this.nombre = nombre;
	}

	public Generos(String nombre, Set libroses) {
		this.nombre = nombre;
		this.libroses = libroses;
	}

	public Integer getIdGenero() {
		return this.idGenero;
	}

	public void setIdGenero(Integer idGenero) {
		this.idGenero = idGenero;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getLibroses() {
		return this.libroses;
	}

	public void setLibroses(Set libroses) {
		this.libroses = libroses;
	}

	@Override
	public String toString() {
		return "Generos [idGenero=" + idGenero + ", nombre=" + nombre + ", libroses=" + libroses + "]";
	}

}
