package modelo.dto.hibernate;
// Generated 15 ene 2026, 19:44:17 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros implements java.io.Serializable {

	private Integer idLibro;
	private Generos generos;
	private String titulo;
	private Set autoreses = new HashSet(0);

	public Libros() {
	}

	public Libros(Generos generos, String titulo) {
		this.generos = generos;
		this.titulo = titulo;
	}

	public Libros(Generos generos, String titulo, Set autoreses) {
		this.generos = generos;
		this.titulo = titulo;
		this.autoreses = autoreses;
	}

	public Integer getIdLibro() {
		return this.idLibro;
	}

	public void setIdLibro(Integer idLibro) {
		this.idLibro = idLibro;
	}

	public Generos getGeneros() {
		return this.generos;
	}

	public void setGeneros(Generos generos) {
		this.generos = generos;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Set getAutoreses() {
		return this.autoreses;
	}

	public void setAutoreses(Set autoreses) {
		this.autoreses = autoreses;
	}

}
