package modelo.dto.hibernate;
// Generated 15 ene 2026, 19:44:17 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Nacionalidades generated by hbm2java
 */
public class Nacionalidades implements java.io.Serializable {

	

	private Integer idNacionalidad;
	private String nombre;
	private Set autoreses = new HashSet(0);

	public Nacionalidades() {
	}

	public Nacionalidades(String nombre) {
		this.nombre = nombre;
	}

	public Nacionalidades(String nombre, Set autoreses) {
		this.nombre = nombre;
		this.autoreses = autoreses;
	}

	public Integer getIdNacionalidad() {
		return this.idNacionalidad;
	}

	public void setIdNacionalidad(Integer idNacionalidad) {
		this.idNacionalidad = idNacionalidad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getAutoreses() {
		return this.autoreses;
	}

	public void setAutoreses(Set autoreses) {
		this.autoreses = autoreses;
	}

	@Override
	public String toString() {
		return "Nacionalidades [idNacionalidad=" + idNacionalidad + ", nombre=" + nombre + ", autoreses=" + autoreses
				+ "]";
	}
}
