package clasesHibernate;
// Generated 28 abr 2026, 18:46:41 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

	private int codigo;
	private String id;
	private String nombre;
	private String iban;
	private String banco;
	private Set pagoses = new HashSet(0);
	private Set matriculases = new HashSet(0);

	public Alumnos() {
	}

	public Alumnos(String id, String nombre, String iban, String banco) {
		this.id = id;
		this.nombre = nombre;
		this.iban = iban;
		this.banco = banco;
	}

	public Alumnos(String id, String nombre, String iban, String banco, Set pagoses, Set matriculases) {
		this.id = id;
		this.nombre = nombre;
		this.iban = iban;
		this.banco = banco;
		this.pagoses = pagoses;
		this.matriculases = matriculases;
	}

	
	
	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public Set getPagoses() {
		return this.pagoses;
	}

	public void setPagoses(Set pagoses) {
		this.pagoses = pagoses;
	}

	public Set getMatriculases() {
		return this.matriculases;
	}

	public void setMatriculases(Set matriculases) {
		this.matriculases = matriculases;
	}

}
