package clasesHibernate;
// Generated 28 abr 2026, 18:46:41 by Hibernate Tools 6.5.1.Final

/**
 * Matriculas generated by hbm2java
 */
public class Matriculas implements java.io.Serializable {

	private int id;
	private Alumnos alumnos;
	private Cursos cursos;

	public Matriculas() {
	}

	public Matriculas(Alumnos alumnos, Cursos cursos) {
		this.alumnos = alumnos;
		this.cursos = cursos;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public Alumnos getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Alumnos alumnos) {
		this.alumnos = alumnos;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

}
