package clasesHibernate;
// Generated 27 abr 2026, 19:16:19 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cursos generated by hbm2java
 */
public class Cursos implements java.io.Serializable {

	private Integer id;
	private String denominacion;
	private BigDecimal cuotaMensual;
	private Set pagoses = new HashSet(0);
	private Set matriculases = new HashSet(0);

	public Cursos() {
	}

	public Cursos(String denominacion, BigDecimal cuotaMensual) {
		this.denominacion = denominacion;
		this.cuotaMensual = cuotaMensual;
	}

	public Cursos(String denominacion, BigDecimal cuotaMensual, Set pagoses, Set matriculases) {
		this.denominacion = denominacion;
		this.cuotaMensual = cuotaMensual;
		this.pagoses = pagoses;
		this.matriculases = matriculases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public BigDecimal getCuotaMensual() {
		return this.cuotaMensual;
	}

	public void setCuotaMensual(BigDecimal cuotaMensual) {
		this.cuotaMensual = cuotaMensual;
	}

	public Set getPagoses() {
		return this.pagoses;
	}

	public void setPagoses(Set pagoses) {
		this.pagoses = pagoses;
	}

	public Set getMatriculases() {
		return this.matriculases;
	}

	public void setMatriculases(Set matriculases) {
		this.matriculases = matriculases;
	}

}
