package clasesHibernate;
// Generated 27 abr 2026, 19:16:19 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;

/**
 * Pagos generated by hbm2java
 */
public class Pagos implements java.io.Serializable {

	private Integer id;
	private Alumnos alumnos;
	private Cursos cursos;
	private String mes;
	private boolean estado;
	private BigDecimal importe;

	public Pagos() {
	}

	public Pagos(Alumnos alumnos, Cursos cursos, String mes, boolean estado, BigDecimal importe) {
		this.alumnos = alumnos;
		this.cursos = cursos;
		this.mes = mes;
		this.estado = estado;
		this.importe = importe;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Alumnos getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Alumnos alumnos) {
		this.alumnos = alumnos;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	public String getMes() {
		return this.mes;
	}

	public void setMes(String mes) {
		this.mes = mes;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

}
